# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  xcode_26:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Run
        run: swift run -v
      - name: Upload .vapi
        uses: actions/upload-artifact@v4
        with:
          name: Generated cl.vapi
          path: vapi/cl.vapi
  linux_6_1:
    runs-on: ubuntu-latest
    container: swift:6.1.2
    steps:
      - uses: actions/checkout@v4
      - name: Version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Run
        run: swift run -v
      - name: Upload .vapi
        uses: actions/upload-artifact@v4
        with:
          name: Generated cl.vapi
          path: vapi/cl.vapi
